[project]
name = "hackathon"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "folium>=0.20.0",
    "geopy>=2.4.1",
    "numpy>=2.3.5",
    "onnxruntime>=1.23.2",
    "pillow>=12.0.0",
    "streamlit>=1.51.0",
    "streamlit-folium>=0.25.3",
]
